www: Makefile - Only include FT AX options if configured in

diff --git a/release/src/router/www/Makefile b/release/src/router/www/Makefile
--- a/release/src/router/www/Makefile
+++ b/release/src/router/www/Makefile
@@ -96,6 +96,22 @@ ifeq ($(RTCONFIG_ROG_UI), y)
 endif
 #endif
 
+# Only include FreshTomato AX options if configured in.
+ifneq ($(TCONFIG_FTAX),y)
+	cd $(INSTALLDIR)/www && \
+	for F in $(wildcard *.asp *.js *.jsx *.jsz *.dict); do \
+		sed -i $$F -e "/FTAX-BEGIN/,/FTAX-END/d"; \
+	done
+endif
+
+# FreshTomato AX options - clean up
+	cd $(INSTALLDIR)/www && \
+	for F in $(wildcard *.asp *.js *.jsx *.jsz *.dict *.html); do \
+		[ -f $(INSTALLDIR)/www/$$F ] && sed -i $$F \
+		-e "/FTAX-BEGIN/d"	-e "/FTAX-END/d" \
+		|| true; \
+	done
+
 ifeq ($(BUILD_NAME),$(filter $(BUILD_NAME), $(QIS_V2)))
 	cp $(TOP)/www/sysdep/FUNCTION/QIS_V2/QIS_wizard.htm $(INSTALLDIR)/www/QIS_wizard.htm
 	cp $(TOP)/www/sysdep/FUNCTION/QIS_V2/images $(INSTALLDIR)/www/ -rf
